name: user_repository
description: A new Flutter package project.
version: 0.0.1
homepage: mehade.dev
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  cloud_firestore: ^3.1.5
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  matrix_lints: 
    path: ../matrix_lints/


