name: todos
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  auth_service: 
    path: packages/auth_service
  firebase_core: ^1.10.5
  flex_color_scheme: ^4.1.1
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_slidable: ^1.1.0
  freezed_annotation: ^1.1.0
  google_fonts: ^2.1.0
  matrix_ui: 
    path: packages/matrix_ui
  timeago: ^3.1.0
  todo_repository: 
    path: packages/todo_repository
  user_repository: 
    path: packages/user_repository
  

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^1.1.0
  matrix_lints: 
    path: packages/matrix_lints


flutter:
  uses-material-design: true
