name: todo_repository
description: A new Flutter package project.
version: 0.0.1
homepage: mehade.dev

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^3.1.4
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^1.1.0
  matrix_lints: 
    path: ../matrix_lints
