import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'auth_user.freezed.dart';

/// [AuthUser] is the model for the user of the app.
/// It contains the the current user's information.
/// Each, [AuthUser] will be stored in the Database.
/// And, we can the user's information from the database by using the [uid].
@freezed
class AuthUser with _$AuthUser {
  const factory AuthUser({
    /// The user's unique ID [uid]
    /// It is generated by Firebase and is unique for each user
    /// And, It is used to identify the user in the database
    ///
    required final String uid,
    final String? email,
    final String? displayName,
    final String? photoUrl,
    final DateTime? lastSignIn,
    final DateTime? createdAt,
  }) = _AuthUser;
}
